### ISSUE TITLE
Can't delete client from the clientRepository for some reason

### ISSUE THREAD

**Issue by haxoc** [haxoc/2020-CISC-191-Final-Project#7]

**Comment by chesteraustin** [comment]
After latest build, "Remove Client" button works as intended.

![image](https://user-images.githubusercontent.com/2084023/89473733-7936db00-d738-11ea-8be4-19523d261679.png)


![image](https://user-images.githubusercontent.com/2084023/89473763-8e136e80-d738-11ea-90ac-fce9cabe7245.png)
